version: '3.3'

services:
  app:
    image: node:16-alpine
    working_dir: /app
    # command: sh -c "npm i && npm run start:dev"
    command: sh -c "npm i && npm run build && npx typeorm migration:run && npm run seed && npm run start:dev"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-3306}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-secret}
      DB_NAME: ${DB_NAME:-blah}
    volumes:
      - ${PWD:-./}:/app
    ports:
      - 3000:3000

  db:
    image: mariadb:10.5
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-blah}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-secret}

volumes:
  dbdata: